theme: minima
title: Ciclismo de Montaña
author: Jair Futema
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  El ciclismo de Montaña es una de las actividades de moda ya que te permite
  gozar de una exelente salud y cuerpo sano, ademas de liberer estres del dia a dia

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
